---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Create OS user and group
  ansible.builtin.import_tasks: os-user.yml

- name: Install Nexus
  ansible.builtin.import_tasks: install.yml

- name: Configure SELinux
  when:
    - _nexus_ce_configure_selinux
  ansible.builtin.include_tasks: selinux.yml

- name: Configure service
  ansible.builtin.import_tasks: service.yml

- name: Configure firewalld
  when:
    - nexus_ce_configure_firewall
    - _nexus_ce_firewall_type == 'firewalld'
  ansible.builtin.include_tasks: firewalld.yml

- name: Configure UFW
  when:
    - nexus_ce_configure_firewall
    - _nexus_ce_firewall_type == 'ufw'
  ansible.builtin.include_tasks: ufw.yml

- name: Configure Nexus
  ansible.builtin.import_tasks: configure.yml
