---
- name: Allow Nexus port in UFW
  become: true
  community.general.ufw:
    port: "{{ nexus_ce_listening_port }}"
    state: enabled
    rule: allow
    proto: tcp
    comment: "Allow Nexus port"
