---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: ce_install 
  description: |
    This role installs Nexus Repository Manager Community Edition on Linux systems.

    A reverse proxy should be configured prior to running this role.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy
        - focal

collections:
  - ansible.posix
  - community.general
  - trippsc2.general

dependencies: []
