---
_nexus_ce_configure_selinux: "{{ nexus_ce_configure_selinux | default(_nexus_ce_default_configure_selinux) }}"
_nexus_ce_firewall_type: "{{ nexus_ce_firewall_type | default(_nexus_ce_default_firewall_type) }}"

_nexus_ce_tmp_path: "{{ nexus_ce_tmp_path | default(_nexus_ce_default_tmp_path) }}"

_nexus_ce_default_repositories:
  - maven-releases
  - maven-snapshots
  - maven-central
  - maven-public
  - nuget-hosted
  - nuget.org-proxy
  - nuget-group
