---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/ce_install/.aar_doc.yml
      - roles/ce_install/README.md
      - roles/ce_install/meta/argument_specs.yml
      - roles/ce_install/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.nexus'
jobs:
  docs_ce_install:
    name: Generate ce_install role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.nexus'
      role_name: 'ce_install'
